- name: Include a role from a collection
  hosts: preprod-study-ansible-704
  become: true
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: main_task
        tasks_from: main.yml
