- name: "Drop existed database"
  community.postgresql.postgresql_db:
    state: absent
    name: >-
      {{ db_name }}
  become: true
  become_user: postgres

- name: "Create database"
  community.postgresql.postgresql_db:
    state: present
    name: >-
      {{ db_name }}
  become: true
  become_user: postgres

- name: Create table in database
  community.postgresql.postgresql_table:
    db: >-
      {{ db_name }}
    name: >-
      {{ table_name }}
    columns: >-
      {{ db_schema }}

  become: true
  become_user: postgres
