- name: outter loop
  ansible.builtin.set_fact:
    sorted_result: "{{ sorted_result + [item.value] }}"
  loop: >-
    {{  outer_item  | 
        dict2items  |
        selectattr('key', 'match', 'query_all_results')
    }}
