- name: Login and use the resulting token
  community.hashi_vault.vault_login:
    url: "{{ URL }}"
    auth_method: ldap
    username: "{{ user }}"
    password: "{{ user_password }}"
  register: login_data

- name: Write/create a secret
  community.hashi_vault.vault_kv2_write:
    url: "{{ URL }}"
    engine_mount_point: creds
    path: "postgresql/lessons/ansible"
    auth_method: token
    token: "{{ login_data |
      community.hashi_vault.vault_login_token }}"
    data: >-
      {{
          sql_data.query_result[0]
      }}
  check_mode: true
