- name: Gathering facts
  ansible.builtin.service_facts:

- name: Disable firewalld if existed
  debug:
    msg: "Disabling firewalld"
  changed_when: true
  when: ansible_facts.services["firewalld.service"].status != "not-found"
  notify:
    - disable firewalld

- name: Disable iptables if existed
  debug:
    msg: "Disabling iptables"
  changed_when: true
  when: ansible_facts.services["iptables.service"].status != "not-found"
  notify:
    - disable iptables

- name: "Flush all handlers defined in this playbook"
  ansible.builtin.meta: flush_handlers
