psql_repos:
  - https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm

psql_install:
- postgresql16-contrib
- postgresql16
- postgresql16-devel
- postgresql16-libs
- python3-psycopg2

psql_dependency:
- wget
- ca-certificates