- name: get psql status
  ansible.builtin.systemd:
    name: >-
      {{ postgresql_service }}
  register: psql16
  listen: get psql16 status

- name: psql-16 status_check
  ansible.builtin.assert:
    that:
      - psql16.status.ActiveState == "active"
    fail_msg: "service is not runned"
    success_msg: "service is active"
  listen: get psql16 status
